add ability to run tests from generic makefile

diff --git a/tests/common/Makefile b/tests/common/Makefile
--- a/tests/common/Makefile
+++ b/tests/common/Makefile
@@ -2,20 +2,25 @@ SBCC = ../../sbcc
 AS = riscv64-unknown-elf-as
 LD = riscv64-unknown-elf-ld
 RISCV_ARGS = -march=rv64g
+sh=zsh
 
 COMMON_DIR = ../common
-GCOV_BASE = ./coverage
+SBCC_BUILD_DIR = ../../build
+COVERAGE_BASE_DIR = ./coverage
 
-.DEFAULT_GOAL = $(notdir $(patsubst %/,%,$(CURDIR))).elf
+TEST_NAME = $(notdir $(patsubst %/,%,$(CURDIR)))
+programs: $(TEST_NAME).output
+
+$(info "DEF: $(.DEFAULT_GOAL)")
 
 %.S: %.sb
-	$(eval COV_OUT_DIR = $(GCOV_BASE)/$(basename $@)/)
-	mkdir -p $(COV_OUT_DIR)
-	$(info "GCOV_DIR: $(COV_OUT_DIR)")
+	$(eval COV_DEST_DIR = $(COVERAGE_BASE_DIR)/$(basename $@))
+	mkdir -p $(COV_DEST_DIR)
 	$(info "building file $@ from $<")
-	@export GCOV_PREFIX = $(COV_OUT_DIR) && $(SBCC) -i $^ -o $(basename $@).S -I $(COMMON_DIR) -I $(shell dirname $@)
-	@mkdir -p $(shell dirname $(COVERAGE_DIR)/$@)
-	@geninfo $(COV_OUT_DIR) -b ".." -o $(COV_OUT_DIR)/$(basename $@).cov
+	$(SBCC) -i $^ -o $(basename $@).S -I $(COMMON_DIR) -I $(shell dirname $@)
+	@mkdir -p $(COV_DEST_DIR)
+	cp $(SBCC_BUILD_DIR)/*.gcda $(COV_DEST_DIR)
+	geninfo --build-directory $(SBCC_BUILD_DIR) $(COV_DEST_DIR) -o $(COV_DEST_DIR)/$(basename $@).cov
 
 
 # all test object files must have one and only one substratum source file
@@ -28,27 +33,23 @@ GCOV_BASE = ./coverage
 	$(MAKE) $(SRCS:.sb=.o)
 	$(LD) -T ../link.lds -o $@ $(SRCS:.sb=.o)
 
+%.output: %.txt %.elf
+	$(eval ENTRY_POINT=$(shell riscv64-unknown-elf-readelf --file-header $(word 2,$^) | grep "Entry point address" | grep -Eo "0x[0-9abcdef]+"))
+	$(eval $(shell qemu-system-riscv64 -machine virt -nographic -bios $(word 2,$^) -device loader,addr=$(ENTRY_POINT),cpu-num=0>$@))
+	if [ `diff $@ $<` ]; then \
+		echo "Test failed";\
+		echo "output:";\
+		echo $@;\
+		exit 1;\
+		else\
+		echo "Test passed";\
+	fi
+
 clean:
 	rm -f *.S
 	rm -f *.o
 	rm -f *.elf
+	rm -f *.output
 	rm -rf coverage
-
-
-# @for test in $(SBCC_TESTS) ; do \
-# 		ls $${test}/*.sb | xargs -I {} echo {} | cut -d'.' -f2 | xargs -I {} make .{}.o;\
-# 		 -T ./link.lds -o $${test}/$${test}.elf `ls ./common/*.o` `ls $${test}/*.o`;\
-# 		ENTRY_POINT=`readelf --file-header $${test}/$${test}.elf | grep "Entry point address" | grep -Eo "0x[0-9abcdef]+"`;\
-# 		VM_OUTPUT=`qemu-system-riscv64 -machine virt -nographic -bios $${test}/$${test}.elf -device loader,addr=$$ENTRY_POINT,cpu-num=0`;\
-# 		diff <(echo "$$VM_OUTPUT") <(cat "$${test}/$${test}.txt");\
-# 		DIFF_RESULT=$$?;\
-# 		if [ $$DIFF_RESULT -eq 0 ]; then \
-# 			echo "Test $${test} passed"; else \
-# 			echo "Test $${test} failed";\
-# 			echo "output:";\
-# 			echo "$$VM_OUTPUT";\
-# 			exit 1;\
-# 		fi ;\
-# 	done
 
 
